using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

#nullable disable
public class nameselect : MonoBehaviour
{
    public InputField playerNameInput;
    private string playerName;
    public GameObject background;
    private Image fadesr;
    private float ftime;
    private float time;
    public GameObject fadepannel;
    public GameObject helppannel;
    private bool click1;
    private bool click2;

    // Start is called before the first frame update
    private void Start()
    {
        this.playerName = this.playerNameInput.GetComponent<InputField>().text;
        this.fadepannel = GameObject.Find("Canvas").transform.Find("fade").gameObject;
        this.click1 = false;
        this.click2 = false;
        this.continueButton.SetActive(false);
        this.StartCoroutine(this.FadeIn());
    }

    // Update is called once per frame
    private void Update()
    {
        if (!Input.GetKeyDown(KeyCode.A) || !Input.GetKeyDown(KeyCode.LeftControl) || !((Object)this.playerNameInput != (Object)null))
            return;
        this.playerNameInput.text = "";
    }

    public void OCCB()
    {
        if (this.click1)
            return;
        this.click1 = true;
        this.playerName = this.playerNameInput.text;
        if (this.playerName.Length > 5)
            return;
        if (this.playerName.Length < 1)
        {
            MonoBehaviour.print((object)"Ïù¥Î¶ÑÏù¥ ÏóÜÎÇòÏöî?");
            this.playerName = "Ìô©ÎèôÏö∞";
            Txt.playername = this.playerName;
            this.StartCoroutine(this.Next());
        }
        Txt.playername = this.playerName;
        this.StartCoroutine(this.Next());
    }

    public IEnumerator Next()
    {
        nameselect nameselect = this;
        nameselect.ftime = 0.7f;
        nameselect.time = 0.0f;
        nameselect.fadepannel.gameObject.SetActive(true);
        nameselect.fadepannel.transform.SetAsLastSibling();
        nameselect.fadesr = nameselect.fadepannel.GetComponent<Image>();
        Color alpha = nameselect.fadesr.color;
        while ((double)alpha.a < 1.0)
        {
            nameselect.time += Time.deltaTime / nameselect.ftime;
            alpha.a = Mathf.Lerp(0.0f, 1f, nameselect.time);
            nameselect.fadesr.color = alpha;
            yield return (object)null;
        }
        nameselect.StartCoroutine(Next2());
    }

    public GameObject nameSetPanel;
    public GameObject continueButton;
    public IEnumerator Next2()
    {
        this.ftime = 0.7f;
        this.time = 0.0f;
        nameSetPanel.SetActive(false);
        this.helppannel.gameObject.SetActive(true);
        this.helppannel.transform.SetAsLastSibling();
        this.fadesr = this.helppannel.GetComponent<Image>();
        Color alpha = this.fadesr.color;
        while ((double)alpha.a < 1.0)
        {
            this.time += Time.deltaTime / this.ftime;
            alpha.a = Mathf.Lerp(0.0f, 1f, this.time);
            this.fadesr.color = alpha;
            yield return (object)null;
        }
        continueButton.SetActive(true);
    }

    public void helpclick()
    {
        if (this.click2)
            return;
        this.click2 = true;
        this.StartCoroutine(this.FadeOut());
    }

    public IEnumerator FadeOut()
    {
        this.ftime = 0.7f;
        this.time = 0.0f;

    // üîΩ helppannelÏùò Ïù¥ÎØ∏ÏßÄ Í∞ÄÏ†∏Ïò§Í∏∞
        Image helpImage = this.helppannel.GetComponent<Image>();
        Color helpAlpha = helpImage.color;

    // üîΩ Ï†êÏ†ê Ìà¨Î™ÖÌïòÍ≤å
        while ((double)helpAlpha.a > 0.0)
        {
            this.time += Time.deltaTime / this.ftime;
            helpAlpha.a = Mathf.Lerp(1f, 0.0f, this.time);
            helpImage.color = helpAlpha;
            yield return null;
        }

        this.helppannel.SetActive(false);

    // fadepannelÏùÑ Îã§Ïãú Î∂àÎü¨ÏÑú Ïû•Î©¥ Ï†ÑÌôò Ïó∞Ï∂úÎèÑ Ìï®Íªò
        this.fadepannel.SetActive(true);
        this.fadesr = this.fadepannel.GetComponent<Image>();
        Color fadeAlpha = this.fadesr.color;
        fadeAlpha.a = 0f;
        this.fadesr.color = fadeAlpha;

        this.time = 0.0f;

        while ((double)fadeAlpha.a < 1.0)
        {
            this.time += Time.deltaTime / this.ftime;
            fadeAlpha.a = Mathf.Lerp(0f, 1f, this.time);
            this.fadesr.color = fadeAlpha;
            yield return null;
        }

    // Ïî¨ Ï†ÑÌôò
        StartCoroutine(this.scene());
    }


    public IEnumerator FadeIn()
    {
        this.ftime = 0.7f;
        this.time = 0.0f;
        this.fadesr = this.fadepannel.GetComponent<Image>();
        Color alpha = this.fadesr.color;
        while ((double)alpha.a > 0.0)
        {
            this.time += Time.deltaTime / this.ftime;
            alpha.a = Mathf.Lerp(1f, 0.0f, this.time);
            this.fadesr.color = alpha;
            yield return (object)null;
        }
        this.fadepannel.gameObject.SetActive(false);
        yield return (object)null;
    }

    public IEnumerator scene()
    {
        SceneManager.LoadScene("MainGame");
        yield return (object)null;
    }

}
